### ISSUE TITLE
The generator of edit sequence

### ISSUE THREAD

**Issue by Ringbo** [Tbabm/CUP#2]
Dear authors.

Thanks for your great work. Recently, we are trying to follow CUP and train your model on our dataset. While it seems that you did not provide the edit sequence generator. To avoid potential bias, if it’s convenient, could you provide the related code? Thanks a lot.

Best
Bo.

**Comment by Tbabm** [comment]
Hi @Ringbo,

I just updated the repo and added the scripts for constructing edit sequences.
Please see [here](https://github.com/Tbabm/CUP#scripts-for-constructing-edit-sequences) for more information and [here](https://github.com/Tbabm/CUP/blob/master/tests/utils/test_edit.py) for how to construct edit sequences from code snippets.

Sorry for my late reply. Hope this could help.

**Comment by Tbabm** [comment]
Hi @Ringbo,

I just updated the repo and added the scripts for constructing edit sequences.
Please see [here](https://github.com/Tbabm/CUP#scripts-for-constructing-edit-sequences) for more information and [here](https://github.com/Tbabm/CUP/blob/master/tests/utils/test_edit.py) for how to construct edit sequences from code snippets.

Sorry for my late reply. Hope this could help.

**Comment by Ringbo** [comment]
> Hi @Ringbo,
> 
> I just updated the repo and added the scripts for constructing edit sequences.
> Please see [here](https://github.com/Tbabm/CUP#scripts-for-constructing-edit-sequences) for more information and [here](https://github.com/Tbabm/CUP/blob/master/tests/utils/test_edit.py) for how to construct edit sequences from code snippets.
> 
> Sorry for my late reply. Hope this could help.

Thanks!
