### ISSUE TITLE
Some questions about datasets.

### ISSUE THREAD

**Issue by jfdaiow** [Tbabm/CUP#3]
Dear authors.

Thanks for your great work. Recently, our group is trying to train your model with our dataset. I see there are a lot of "idx" in .jsonl files of your dataset, but we can not understand what is this for. To avoid potential bias, could you tell us what "idx" means? In addition, there are some .pkl files in your dataset, could you tell us how are these files generated? Thanks a lot.

Best wishes

**Comment by Tbabm** [comment]
1. For "idx", do you mean the "index" field of each sample? This field will not be used during training, validation and testing, so you do not need to create this field for your data.
2. For .pkl files, they are pre-trained word embeddings. Please refer to here (https://github.com/Tbabm/CUP#build-vocab-yourself) for how to generate them for your vocabulary.

**Comment by jfdaiow** [comment]
Thanks for your reply.
